### ISSUE TITLE
Nice idea

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [wiligangster/CrashFixer#1]
Do the plugin block that ios crash symbol that works on windows 10 ? I prevented crashes until now by editing the PMMP source code everytime i updated, and it was really annoying lol.

**Comment by yesitswalid** [comment]
Yes. why modified the software directly? while minecraft will soon fix it

**Comment by TDMidkwhatisxd** [comment]
Im not too up to date with pmmp api, i gave up learning it since it always change xd

**Comment by TDMidkwhatisxd** [comment]
Anything i need i code directly into software

For example deadbush glitch -...-'
